# Files and directories
music_directory    "~/General/Lithium"
playlist_directory "~/.local/state/mpd/playlists"
db_file            "~/.local/state/mpd/database"
log_file           "~/.local/state/mpd/log"
pid_file           "~/.local/state/mpd/pid"
state_file         "~/.local/state/mpd/state"
sticker_file       "~/.local/state/mpd/sticker.sql"

# Network setup
bind_to_address    "127.0.0.1"
port               "6600"
restore_paused     "yes"
auto_update        "yes"

# Native PipeWire Output
# audio_output {
    # type            "pipewire"
    # name            "PipeWire Sound Server"
# }

audio_output {
        type          "alsa"
        name          "ALSA sound card"
        # Optional
        #device        "iec958:CARD=Intel,DEV=0"
        #mixer_control "PCM"
}

# Optional: Visualizer output (for ncmpcpp)
audio_output {
    type            "fifo"
    name            "Visualizer feed"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}

